# Generated by Django 5.2.11 on 2026-02-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
        migrations.AddField(
            model_name='rides',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Published'), ('2', 'Cancelled')], default='0', max_length=1),
        ),
    ]
