# Generated by Django 5.2.11 on 2026-02-19 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_userprofile_options_rides_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rides',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Rides'},
        ),
        migrations.AddField(
            model_name='riderequest',
            name='seats_requested',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rides',
            name='seats_available',
            field=models.IntegerField(choices=[(0, '0 seats'), (1, '1 seat'), (2, '2 seats'), (3, '3 seats'), (4, '4 seats'), (5, '5 seats')], default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
