# Generated by Django 5.2.11 on 2026-02-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_rides_options_riderequest_seats_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='pickup_notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rides',
            name='seats_available',
            field=models.IntegerField(choices=[(0, '0 seats'), (1, '1 seat'), (2, '2 seats'), (3, '3 seats'), (4, '4 seats'), (5, '5 seats')], default=1),
        ),
    ]
