# Generated by Django 5.2.11 on 2026-02-21 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_rides_pickup_notes_alter_rides_seats_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='seats_requested',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='rides',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rides',
            name='origin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rides',
            name='seats_available',
            field=models.IntegerField(choices=[(1, '1 seat'), (2, '2 seats'), (3, '3 seats'), (4, '4 seats')], default=1),
        ),
    ]
