# Generated by Django 5.2.11 on 2026-02-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Accepted'), ('2', 'Rejected'), ('3', 'Cancelled by passenger'), ('4', 'Completed'), ('5', 'Cancelled by driver')], default='0', max_length=1),
        ),
    ]
